# Generated by Django 4.2.14 on 2024-08-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_book_overdue'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='returntime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
