# Generated by Django 4.2.14 on 2024-08-11 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_book_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patron',
            name='description',
        ),
    ]
