# Generated by Django 4.2.14 on 2024-08-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_patron_options_alter_patron_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patron',
            options={},
        ),
        migrations.AlterModelManagers(
            name='patron',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='patron',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='patron',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patron',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='patron',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='patron',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='patron',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='patron',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='patron',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='patron',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='patron',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
